# use of $./xmasbot -yaml "settings.yaml"
# irc server 1
- nick: "xmas88" # mandatory field
  channels: ["#spamtest"]  # channel with channel password after the ":"
  server: irc.ptirc.org:6697 # default if omitted
  nossl: false # true to disable SSL for irc
  nocheck: false # disble ssl verification for self signed certs
  password: "" # irc server password
  saslnick: "" # sasl username
  saslpass: "" # sasl password
  prefix: '!' # default if omitted
  email: "example@example.com" # mandatory field
  nominatim: https://nominatim.openstreetmap.org # default if omitted 
  nolimit: false # true will disable protection against flood kick attack
  colors: true # decorate irc messages
  debug: false
